project_id = "ai-insight-navigator"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 17

[auth]
enabled = true
enable_signup = false
site_url = "https://nexation.ir"
additional_redirect_urls = ["http://localhost:3000/**", "https://nexation.ir/**", "https://*.vercel.app/**"]
